<a href="https://colab.research.google.com/github/drjgouveia/data-science-and-ml/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data preprocessing

Importing libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing dataset

In [ ]:
dataset = pd.read_csv("restaurant_profit.csv")

In [ ]:
dataset.head()

Miscellaneous Expenses  Food Innovation  Advertisement     City     Profit
0               138671.80        167497.20      475918.10  Chicago  202443.83
1               153151.59        164745.70      448032.53   Mumbai  201974.06
2               102919.55        155589.51      412068.54    Tokyo  201232.39
3               120445.85        146520.41      387333.62  Chicago  193083.99
4                93165.77        144255.34      370302.42    Tokyo  176369.94

In [ ]:
dataset.columns

Index(['Miscellaneous Expenses', 'Food Innovation', 'Advertisement', 'City',
       'Profit'],
      dtype='object')

In [ ]:
dataset.count()

Miscellaneous Expenses    50
Food Innovation           50
Advertisement             50
City                      50
Profit                    50
dtype: int64

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Miscellaneous Expenses  50 non-null     float64
 1   Food Innovation         50 non-null     float64
 2   Advertisement           50 non-null     float64
 3   City                    50 non-null     object 
 4   Profit                  50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [ ]:
dataset.describe()

Miscellaneous Expenses  Food Innovation  Advertisement         Profit
count               50.000000        50.000000      50.000000      50.000000
mean            123118.639600     75869.615600  215159.097800  122194.639200
std              28017.802755     45902.256482  122290.310726   40306.180338
min              53057.140000      2148.000000    4134.000000   24863.400000
25%             105504.875000     42084.370000  133434.132500  100320.902500
50%             124473.795000     75199.080000  216850.240000  118160.190000
75%             146616.180000    103750.800000  303603.085000  149947.977500
max             184419.560000    167497.200000  475918.100000  202443.830000

## Enconding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')

In [ ]:
x = np.array(ct.fit_transform(dataset.iloc[:, 0:-1].values))
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[1.0 0.0 0.0 138671.8 167497.2 475918.1]
 [0.0 1.0 0.0 153151.59 164745.7 448032.53]
 [0.0 0.0 1.0 102919.55 155589.51 412068.54]
 [1.0 0.0 0.0 120445.85 146520.41 387333.62]
 [0.0 0.0 1.0 93165.77 144255.34 370302.42]
 [1.0 0.0 0.0 101588.71 134024.9 366995.36]
 [0.0 1.0 0.0 148972.87 136763.46 131850.82]
 [0.0 0.0 1.0 147304.06 132446.13 328010.68]
 [1.0 0.0 0.0 150492.95 122690.52 315747.29]
 [0.0 1.0 0.0 110453.17 125482.88 309115.62]
 [0.0 0.0 1.0 112368.11 104061.08 233294.95]
 [0.0 1.0 0.0 93564.61 102819.96 253878.55]
 [0.0 0.0 1.0 129094.38 96011.75 253973.44]
 [0.0 1.0 0.0 137269.07 94140.39 256798.93]
 [0.0 0.0 1.0 158321.42 122091.24 260646.92]
 [1.0 0.0 0.0 124390.84 116671.61 265910.23]
 [0.0 1.0 0.0 123371.55 80161.11 268480.06]
 [1.0 0.0 0.0 146851.58 96805.16 286708.31]
 [0.0 0.0 1.0 115949.79 93897.16 299053.57]
 [1.0 0.0 0.0 155288.11 88567.7 4134.0]
 [0.0 1.0 0.0 115641.3 78401.86 302798.47]
 [1.0 0.0 0.0 155547.43 80537.47 303871.29]
 [0.0 0.0 1.0 124556.75 76142.

Splitting the dataset

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
len(x_train)

40

In [ ]:
len(x_test)

10

# Training the model

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(x_train, y_train)

LinearRegression()

# Predicting the Test set results

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
print(y_pred)
print(y_test)

[113197.20159798 142764.27760812 142629.73845172  82158.09851261
 188719.48221046 126343.24230164  78033.6920968  108973.73374691
 124151.43533011 178103.06569543]
[113464.38 154441.4  156303.95  87980.83 201232.39 115190.31  91411.06
 107665.56 120534.25 176369.94]


In [ ]:
df = pd.DataFrame()
df["y_actual"] = y_test
df["y_pred"] = y_pred

In [ ]:
df

y_actual         y_pred
0  113464.38  113197.201598
1  154441.40  142764.277608
2  156303.95  142629.738452
3   87980.83   82158.098513
4  201232.39  188719.482210
5  115190.31  126343.242302
6   91411.06   78033.692097
7  107665.56  108973.733747
8  120534.25  124151.435330
9  176369.94  178103.065695